### Get all students
GET http://localhost:3000/students

### Create new student
POST http://localhost:3000/students
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Hamidu",
  "email": "johnh@gmail.com",
  "major": "Computer Science",
  "gpa": 3.8,
  "year": 2
}

### Get single student
GET http://localhost:3000/students/PUT_REAL_ID_HERE

### Update student
PUT http://localhost:3000/students/PUT_REAL_ID_HERE
Content-Type: application/json

{
  "major": "Software Engineering"
}

### Delete student
DELETE http://localhost:3000/students/PUT_REAL_ID_HERE


### Get all courses
GET http://localhost:3000/courses

### Create new course
POST http://localhost:3000/courses
Content-Type: application/json

{
  "courseName": "Data Structures",
  "courseCode": "CSE310",
  "instructor": "Brother Hellman",
  "credits": 4
}

### Get single course
GET http://localhost:3000/courses/PUT_REAL_ID_HERE

### Update course
PUT http://localhost:3000/courses/PUT_REAL_ID_HERE
Content-Type: application/json

{
  "credits": 4
}

### Delete course
DELETE http://localhost:3000/courses/PUT_REAL_ID_HERE